export enum TipoPensamiento {
    PENSAMIENTO_PERFIL ='', // ESTILOS PENSAMIENTO QUE SE PRESENTA EN EL PEFIL
    PENSAMIENTO_ALEATORIO = 'divPensamientoAmarillo tamanoPensamientoAleatorio regular', // ESTILOS PENSAMIENTO ALEATORIO
    PENSAMIENTO_PRIVADO_CREACION = '', // ESTILOS PENSAMIENTO PARA CREACION O MODIFICACION DE UN PENSAMIENTO PRIVADO
    PENSAMIENTO_PUBLICO_CREACION = 'divPensamientoAmarillo tamanoPensamientoAleatorio', // ESTILOS PENSAMIENTO PARA CREACION O MODIFICACION DE UN PENSAMIENTO PUBLICO
}

export enum EstiloItemPensamiento {
    ITEM_ALEATORIO='regular letra-3-con-interlineado-1 txt-negro textPensamiento', /// ESTILOS DE CSS ITEM PENSAMIENTO
}